# Generated by Django 5.1.2 on 2024-10-20 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0003_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_show_session",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "show_session")},
        ),
    ]
