# Generated by Django 5.1.2 on 2024-10-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0004_remove_ticket_unique_ticket_seat_show_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtheme",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
