# Generated by Django 5.1.2 on 2024-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0005_alter_showtheme_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(null=True, upload_to="astronomy_show_image_path"),
        ),
    ]
