# Generated by Django 5.1.2 on 2024-10-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0006_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="show_theme",
            field=models.ManyToManyField(
                blank=True, related_name="show_themes", to="planetarium.showtheme"
            ),
        ),
    ]
